### ISSUE TITLE
List migration status of components

### ISSUE THREAD

**Issue by rcannood** [viash-hub/rnaseq#4]
In every component, list the path and commit sha of what it is based on. E.g.:

```yaml
functionality:
  name: gffread
  info:
    migration_info:
      git_repo: https://github.com/nf-core/modules.git
      paths: [modules/nf-core/gffread/main.nf, modules/nf-core/gffread/meta.yml]
      last_sha: 5e34754d42cd2d5d248ca8673c0a53cdf5624905
```

This could allow us to automatically keep track of components which components need updating.
